### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by thispsj** [thispsj-lab/pr-actions#13]
Hey 👋 I'm trying out task lists !

## Linked Issues

- [ ] [#12](https://github.com)
- [X] [#6](https://github.com) 
- [ ] [#5](https://gitlab.com)

## Possible fixes
- [ ] Open a issue in [github/primer](https://github.com) repository.
- [x] Ask @thispsj-lab/everyone to review the files.
- [X] Fix the bug in `tests.js`.
- [ ] Write a workflow to test the code in a Pull Request.
